/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardsProfessionalRouteImport } from './routes/dashboards/professional'
import { Route as DashboardsMedicalRouteImport } from './routes/dashboards/medical'
import { Route as DashboardsGymRouteImport } from './routes/dashboards/gym'
import { Route as DashboardsEducationRouteImport } from './routes/dashboards/education'
import { Route as DashboardsBeautyRouteImport } from './routes/dashboards/beauty'
import { Route as BookTenantIdRouteImport } from './routes/book.$tenantId'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsProfessionalRoute = DashboardsProfessionalRouteImport.update({
  id: '/dashboards/professional',
  path: '/dashboards/professional',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsMedicalRoute = DashboardsMedicalRouteImport.update({
  id: '/dashboards/medical',
  path: '/dashboards/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsGymRoute = DashboardsGymRouteImport.update({
  id: '/dashboards/gym',
  path: '/dashboards/gym',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsEducationRoute = DashboardsEducationRouteImport.update({
  id: '/dashboards/education',
  path: '/dashboards/education',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsBeautyRoute = DashboardsBeautyRouteImport.update({
  id: '/dashboards/beauty',
  path: '/dashboards/beauty',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTenantIdRoute = BookTenantIdRouteImport.update({
  id: '/book/$tenantId',
  path: '/book/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/book/$tenantId': typeof BookTenantIdRoute
  '/dashboards/beauty': typeof DashboardsBeautyRoute
  '/dashboards/education': typeof DashboardsEducationRoute
  '/dashboards/gym': typeof DashboardsGymRoute
  '/dashboards/medical': typeof DashboardsMedicalRoute
  '/dashboards/professional': typeof DashboardsProfessionalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/book/$tenantId': typeof BookTenantIdRoute
  '/dashboards/beauty': typeof DashboardsBeautyRoute
  '/dashboards/education': typeof DashboardsEducationRoute
  '/dashboards/gym': typeof DashboardsGymRoute
  '/dashboards/medical': typeof DashboardsMedicalRoute
  '/dashboards/professional': typeof DashboardsProfessionalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/book/$tenantId': typeof BookTenantIdRoute
  '/dashboards/beauty': typeof DashboardsBeautyRoute
  '/dashboards/education': typeof DashboardsEducationRoute
  '/dashboards/gym': typeof DashboardsGymRoute
  '/dashboards/medical': typeof DashboardsMedicalRoute
  '/dashboards/professional': typeof DashboardsProfessionalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/customers'
    | '/dashboard'
    | '/demo'
    | '/features'
    | '/integrations'
    | '/login'
    | '/pricing'
    | '/resources'
    | '/security'
    | '/signup'
    | '/solutions'
    | '/admin/dashboard'
    | '/admin/login'
    | '/book/$tenantId'
    | '/dashboards/beauty'
    | '/dashboards/education'
    | '/dashboards/gym'
    | '/dashboards/medical'
    | '/dashboards/professional'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/customers'
    | '/dashboard'
    | '/demo'
    | '/features'
    | '/integrations'
    | '/login'
    | '/pricing'
    | '/resources'
    | '/security'
    | '/signup'
    | '/solutions'
    | '/admin/dashboard'
    | '/admin/login'
    | '/book/$tenantId'
    | '/dashboards/beauty'
    | '/dashboards/education'
    | '/dashboards/gym'
    | '/dashboards/medical'
    | '/dashboards/professional'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/customers'
    | '/dashboard'
    | '/demo'
    | '/features'
    | '/integrations'
    | '/login'
    | '/pricing'
    | '/resources'
    | '/security'
    | '/signup'
    | '/solutions'
    | '/admin/dashboard'
    | '/admin/login'
    | '/book/$tenantId'
    | '/dashboards/beauty'
    | '/dashboards/education'
    | '/dashboards/gym'
    | '/dashboards/medical'
    | '/dashboards/professional'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  FeaturesRoute: typeof FeaturesRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResourcesRoute: typeof ResourcesRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  SolutionsRoute: typeof SolutionsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BookTenantIdRoute: typeof BookTenantIdRoute
  DashboardsBeautyRoute: typeof DashboardsBeautyRoute
  DashboardsEducationRoute: typeof DashboardsEducationRoute
  DashboardsGymRoute: typeof DashboardsGymRoute
  DashboardsMedicalRoute: typeof DashboardsMedicalRoute
  DashboardsProfessionalRoute: typeof DashboardsProfessionalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/professional': {
      id: '/dashboards/professional'
      path: '/dashboards/professional'
      fullPath: '/dashboards/professional'
      preLoaderRoute: typeof DashboardsProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/medical': {
      id: '/dashboards/medical'
      path: '/dashboards/medical'
      fullPath: '/dashboards/medical'
      preLoaderRoute: typeof DashboardsMedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/gym': {
      id: '/dashboards/gym'
      path: '/dashboards/gym'
      fullPath: '/dashboards/gym'
      preLoaderRoute: typeof DashboardsGymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/education': {
      id: '/dashboards/education'
      path: '/dashboards/education'
      fullPath: '/dashboards/education'
      preLoaderRoute: typeof DashboardsEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/beauty': {
      id: '/dashboards/beauty'
      path: '/dashboards/beauty'
      fullPath: '/dashboards/beauty'
      preLoaderRoute: typeof DashboardsBeautyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$tenantId': {
      id: '/book/$tenantId'
      path: '/book/$tenantId'
      fullPath: '/book/$tenantId'
      preLoaderRoute: typeof BookTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  FeaturesRoute: FeaturesRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResourcesRoute: ResourcesRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  SolutionsRoute: SolutionsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  BookTenantIdRoute: BookTenantIdRoute,
  DashboardsBeautyRoute: DashboardsBeautyRoute,
  DashboardsEducationRoute: DashboardsEducationRoute,
  DashboardsGymRoute: DashboardsGymRoute,
  DashboardsMedicalRoute: DashboardsMedicalRoute,
  DashboardsProfessionalRoute: DashboardsProfessionalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
